apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ouve
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ouve
    app.kubernetes.io/part-of: byoc-app-mauz
  name: ouve
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: ouve
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: ouve
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-abzw-tenant/byoc-app-mauz/ouve@sha256:2e9d7623afd0848141ddccf3099e61a1c7f5822e0d3d9c52d4858915d52e41ef
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
